# Generated by Django 6.0.5 on 2026-05-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('heading', models.CharField(default='', help_text="e.g. 'Master of Vedic Astrology'", max_length=255)),
                ('description', models.TextField(default='')),
                ('experience_years', models.PositiveIntegerField(default=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='AstrologyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Beginner', max_length=20)),
                ('duration', models.CharField(blank=True, default='', help_text="e.g. '3 Months'", max_length=50)),
                ('mode', models.CharField(blank=True, default='', help_text="e.g. 'Online / Offline'", max_length=50)),
                ('students', models.CharField(blank=True, default='', help_text="e.g. '200+ Enrolled'", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gradient', models.CharField(blank=True, default='linear-gradient(135deg,#1c1638,#4a1472)', max_length=150)),
                ('badge_bg', models.CharField(blank=True, default='rgba(212,175,55,0.15)', max_length=100)),
                ('badge_color', models.CharField(blank=True, default='#d4af37', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Astrology Course',
                'verbose_name_plural': 'Astrology Courses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('service', models.CharField(default='', max_length=150)),
                ('message', models.TextField(default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('emoji', models.CharField(blank=True, default='🔮', help_text='Fallback emoji if no image', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('gradient', models.CharField(blank=True, default='linear-gradient(135deg,#1c1638,#4a1472)', help_text='Background gradient shown when no image is uploaded', max_length=150)),
                ('span_two_columns', models.BooleanField(default=False, help_text='Makes this item span 2 columns in the gallery grid')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('category', models.CharField(blank=True, default='', help_text="e.g. 'Gemstone', 'Rudraksha'", max_length=80)),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji fallback', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('gradient', models.CharField(blank=True, default='linear-gradient(135deg,#1c1638,#4a1472)', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='🔮', help_text='Emoji icon e.g. 🪐', max_length=20)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Lucknow, Uttar Pradesh', max_length=255)),
                ('phone', models.CharField(default='+91 9506619555', max_length=20)),
                ('email', models.EmailField(default='cchengemylife3@gmail.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='919506619555', help_text="Number without '+' for wa.me links", max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField(default='')),
                ('emoji', models.CharField(blank=True, default='🙏', help_text='Avatar emoji', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='anjali.about')),
            ],
            options={
                'verbose_name': 'About Feature',
                'verbose_name_plural': 'About Features',
                'ordering': ['order'],
            },
        ),
    ]
