# Generated by Django 6.0.5 on 2026-05-08 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional')], max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('students_limit', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='anjali_astr_title_122373_idx'), models.Index(fields=['level'], name='anjali_astr_level_64c96e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid Indian phone number', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Kundali', 'Janam Kundali'), ('Marriage', 'Kundali Milan'), ('Career', 'Career Guidance'), ('Vastu', 'Vastu'), ('Numerology', 'Numerology'), ('Course', 'Course Enrollment'), ('Product', 'Product Order')], max_length=100)),
                ('message', models.TextField()),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='anjali_cont_phone_23e083_idx'), models.Index(fields=['email'], name='anjali_cont_email_c30c36_idx'), models.Index(fields=['service'], name='anjali_cont_service_156571_idx'), models.Index(fields=['created_at'], name='anjali_cont_created_cbb425_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='anjali_prod_name_67ffdb_idx'), models.Index(fields=['category'], name='anjali_prod_categor_5b94f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['title'], name='anjali_serv_title_a1a3cb_idx'), models.Index(fields=['is_active'], name='anjali_serv_is_acti_593d39_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='anjali_test_name_891310_idx'), models.Index(fields=['city'], name='anjali_test_city_6cceb8_idx')],
            },
        ),
    ]
